name: Simple GKI Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: The Radical Solution (Add 16GB Swap RAM)
        run: |
          # هنا إحنا بنضحك على السيرفر وبنديله 16 جيجا رامات إضافية من مساحة التخزين
          sudo fallocate -l 16G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo "RAM Memory Info After Swap:"
          free -h

      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm gcc-aarch64-linux-gnu

      - name: Basic Compilation Test
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          
          # تجهيز الإعدادات
          make LLVM=1 LLVM_IAS=1 O=out gki_defconfig
          
          # إجبار الكيرنل من الجذور على إيقاف LTO
          ./scripts/config --file out/.config -d LTO_CLANG_FULL -d LTO_CLANG_THIN -e LTO_NONE
          
          # الحل الجذري التاني: بدل ما نستخدم كل المعالجات وتضغط الرامات، هنخليها تبني على نواتين بس (-j2)
          make LLVM=1 LLVM_IAS=1 O=out LTO=none -j2
